title: "Functional Scala 2019"
description: "Functional Scala 2019 (London Edition) is a free 2-day conference devoted to using the powerful features and libraries of the Scala programming language to build robust, modern, software that is easier to understand and maintain."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.functionalscala.com/" # the base hostname & protocol for your site
title_image: "https://www.functionalscala.com/css/2016_style/img/header-bg.jpg"
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2016_style/img/icon-large.png"

social:
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/FunScala2019

# Build settings
markdown: kramdown
permalink: pretty
